apiVersion: apps/v1

kind: Deployment

metadata:
  name: docker-k8s-website

spec:
  replicas: 3

  selector:
    matchLabels:
      app: docker-k8s-website

  template:
    metadata:
      labels:
        app: docker-k8s-website

    spec:
      containers:
        - name: website
          image: docker-k8s-website:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80